apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.spec.app }}